### ISSUE TITLE
Mesh Loading Error

### ISSUE THREAD

**Issue by RylanJGraham** [CITM-UPC/VertX-Game-Engine#1]
The mesh is giving an error when attempting to build the BakerHouse.fbx. The issue is with the glGenBuffers(1, &_vertex_buffer_id);
    glBindBuffer(GL_ARRAY_BUFFER, _vertex_buffer_id); call in the mesh constructor. I do not believe it is an issue with the asset path, as when I change the asset path it detects the mesh scene as a nullptr.

**Comment by pepcots** [comment]
Hi @RylanJGraham @AdriaPm 
The null reference is because of the method pointer (pointer to the "glBindBuffer" method) has not been initialized.
glewInit() is the responsible to initialize all gl method pointers, but, be sure to call glewInit after creating the gl context (it is done by the SDL window manager)

**Comment by AdriaPm** [comment]
Hi @pepcots 
You hit the nail. That was the issue. Thank you very much!
